= Get Help
:page-aliases: support.adoc

To be successful at writing and publishing AsciiDoc content with Asciidoctor, we encourage you to maintain a dialogue with the project maintainers and other community members.
Don't hesitate to ask questions and discuss any aspects of the project using an appropriate communication channel listed below.
Your feedback helps drive the projects forward by providing use cases, ideas, metrics, and motivation.

NOTE: Each project may provide more focused or preferred communication channels.
Please refer to the help section for the respective project to find those details.

[#chat]
== Project chat

[horizontal]
Platform:: Zulip
URL:: https://chat.asciidoctor.org

*The project chat is the preferred means of communication for all users of Asciidoctor.*
This policy helps keep the project sustainable.
If you want to ask for help, share feedback, or exchange ideas with fellow community members in real time, please do so in the project chat.

The chat also serves as the project forum.
Like a forum, the chat is partitioned into streams.
If you find an ongoing discussion that matches the topic you're interested in, feel free to join that discussion.
Otherwise, please post a new topic in the `#users` stream (*not* the `#community` stream).
Please do not post unrelated questions or comments to an existing topic since that disrupts the discussion and makes answers more difficult to find.

TIP: Please use the filter or search feature to find existing topics before starting a new one.

If you're starting a new topic that relates to a specific project, check if there's a stream for that project and post to that stream instead of the `#users` stream.
For example, if you want to ask a question that only applies to AsciidoctorJ, please create the topic in the `#users/asciidoctorj` stream.
If you aren't sure where to post, you can always start with the `#users` stream and a moderator will relocate the topic if necessary.

The discussions in the project chat are archived and public.
There's no guarantee those logs will be saved indefinitely, though we plan keep them as long as we're permitted to do so.

Keep in mind that people participate in the project chat voluntarily, so please be respectful of their time and interests.
The project chat is not 1-on-1 support.
You're in a public space.

Do not `@` mention someone when writing a message unless a) the subject matter absolutely requires the attention of that person or b) that person has already replied to the topic and is interacting with you.
Using the `@` mention to draw attention to your question is not courteous to that person or fair to others.
You're free to post your message to the community at large (no `@` mention).
If someone has something to share in response, they will do so if and when they have time.
You can reference someone without notifying them using the `@_` prefix, which is considered acceptable conduct.

== Issue tracker

[horizontal]
Platform:: GitHub
URL:: https://github.com/asciidoctor/asciidoctor/issues

IMPORTANT: If the issue does not pertain to Asciidoctor core, please file the issue in the issue tracker for the relevant project.
For example, to file an issue about AsciidoctorJ, please use the issue tracker at https://github.com/asciidoctor/asciidoctorj/issues.

The issue tracker is the preferred channel for reporting verifiable bugs, regressions, and security vulnerabilities, or for making formal, specific, and well-defined change requests.
*Please do not ask questions about how to use the software in the issue tracker.*
Instead, you may direct questions about usage to the <<chat,project chat>>.
Please do not comment on closed issues unless you're adding additional context, such as to report whether the fix worked for you or how you made use of it.
If you post an unproductive comment on an open issue, such as "`What's the status of this issue after X years?`", your comment will be deleted.

Any significant change or decision about the project's software is recorded in the issue tracker.
The issue tracker is also used for planning releases via milestones and labels.

== Social media

[horizontal]
Platform:: Twitter
URL:: https://twitter.com/asciidoctor

If you want to share your experience with Asciidoctor or help promote it, we encourage you to post about it on social media.
When you post about Asciidoctor on Twitter, you can mention the official account for the project, https://twitter.com/asciidoctor[@asciidoctor].
You can also use the https://twitter.com/search?q=%23asciidoctor[#asciidoctor] hashtag to help others find your post or discover others who are talking about it.

[#discuss]
== Discussion list (archived)

[horizontal]
Platform:: Nabble
URL:: https://discuss.asciidoctor.org

In the past, this project used the discussion list for general communication.
During that time, community members asked for help, shared feedback, and exchanged ideas with fellow community members over email.
Since the successful introduction of the <<chat>>, this channel of communication has been archived and is now read only.
You may continue to use it as a knowledge base.
However, all new questions, feedback, announcements, and other general discourse should be directed to the project chat.

== Please be considerate

Please understand that all members of this community are volunteers and support is provided to fellow community members at will and often out of personal interest.
When using these communication channels, we expect you to uphold the xref:code-of-conduct.adoc[Code of Conduct].

If you're seeking professional support, you can ask the project maintainers or other community members if they offer any services.
Otherwise, keep in mind that people participating in this project do not work for you.
