= Get Help

To be successful at writing and publishing AsciiDoc content with Asciidoctor, we encourage you to maintain a dialogue with the project maintainers and other community members.
Don't hesitate to ask questions and discuss any aspects of the project using an appropriate communication channel listed below.
Your feedback helps drive the projects forward by providing use cases, ideas, metrics, and motivation.

NOTE: Each project may provide more focused or preferred communication channels.
Please refer to the help section for the respective project to find those details.

[#chat]
== Project chat

[horizontal]
Platform:: Zulip
URL:: https://chat.asciidoctor.org

If you want to ask for help, share feedback, or exchange ideas with fellow community members in real time, please do so in the project chat.
*The project chat is the preferred means of communication for all Asciidoctor users.*

If you find an ongoing discussion that matches the topic you're interested in, feel free to join that discussion.
Otherwise, please post a new topic in the `#users` stream (*not* the `#community` stream).
Only post to a different stream if you understand the stream's purpose and have determined that your topic is suitable for it.
For example, if you're asking a question specifically about AsciidoctorJ, please post to the `#users/asciidoctorj` stream.

TIP: Please make use of the search feature to find existing topics before starting a new one.

The discussions in the project chat are archived and public.
There's no guarantee those logs will be saved indefinitely, though we plan keep them as long as we're permitted to do so.

Keep in mind that users participate in the project chat voluntarily, so please respect their time.

== Issue tracker

[horizontal]
Platform:: GitHub
URL:: https://github.com/asciidoctor/asciidoctor/issues

IMPORTANT: If the issue does not pertain to Asciidoctor core, please file the issue in the issue tracker for the relevant project.
For example, to file an issue about AsciidoctorJ, please use the issue tracker at https://github.com/asciidoctor/asciidoctorj/issues.

The issue tracker is the preferred channel for reporting verifiable bugs, regressions, and security vulnerabilities or for making formal change requests.
Please direct questions about usage of the software to the project chat instead.
Please do not comment on closed issues unless you're following up to report whether or not the fix worked.

Any significant change or decision about the project is recorded in the issue tracker.
The issue tracker is also used for planning releases via milestones and labels.

== Social media

[horizontal]
Platform:: Twitter
URL:: https://twitter.com/asciidoctor

If you want to share your experience with Asciidoctor or help promote it, we encourage you to post about it on social media.
When you post about Asciidoctor on Twitter, you can mention the official account for the project, https://twitter.com/asciidoctor[@asciidoctor].
You can also use the https://twitter.com/search?q=%23asciidoctor[#asciidoctor] hashtag to help others find your post or discover others who are talking about it.

[#discuss]
== Discussion list (archived)

[horizontal]
Platform:: Nabble
URL:: https://discuss.asciidoctor.org

In the past, this project used the discussion list for general communication.
During that time, community members asked for help, shared feedback, and exchanged ideas with fellow community members over email.
Since the successful introduction of the <<chat>>, this channel of communication has been archived and is now read only.
You may continue to use it as a knowledge base.
However, all new questions, feedback, announcements, and other general discourse should be directed to the project chat.

== Please be considerate

Please understand that all members of this community are volunteers and support is provided to fellow community members at will and often out of personal interest.
When using these communication channels, we expect you to uphold the https://github.com/asciidoctor/.github/blob/main/CODE-OF-CONDUCT.md[Code of Conduct].

If you're seeking professional support, you can ask the project maintainers or other community members if they offer any services.
Otherwise, keep in mind that people participating in this project do not work for you.
